name: Push to master
on:
  push:
    branches:
      - master

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true

permissions:
  id-token: write # allows the JWT to be requested from GitHub's OIDC provider
  contents: write # This is required for actions/checkout and github-script to create tags

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@f4a75cfd619ee5ce8d5b864b0d183aff3c69b55a # v2.13.1
        with:
          egress-policy: audit

      - name: Check out repository code
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@e468171a9de216ec08956ac3ada2f0791b6bd435 # v3.11.1

      - name: Login to DockerHub
        uses: docker/login-action@5e57cd118135c172c3672efd75eb46360885c0ef # v3.6.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Get Release Version
        uses: thebongy/version-check@b88eb2decc2ece667edf2d78665e88254e8403d6
        with:
          file: package.json
          tagFormat: v${version}
          failBuild: true
        id: get_release_version

      - name: Clone enrichment plugin
        run: |
          rm -rf rudder-alerta-enrichment-plugin
          git config --global url."https://${{secrets.PAT}}:x-oauth-basic@github.com/rudderlabs".insteadOf "https://github.com/rudderlabs"
          git clone -b "$(cat RUDDER_ENRICH_PLUGIN_BRANCH_NAME)" https://github.com/rudderlabs/rudder-alerta-enrichment-plugin.git

      - name: Build, scan and push
        uses: rudderlabs/build-scan-push-action@6da37ae441adc487f22920ca87bf52d6fd715fd3 # v1.5.3
        with:
          context: .
          push: true
          tags: rudderlabs/alerta:${{ steps.get_release_version.outputs.releaseVersion }}
          build-args: |
            GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}
            COMMIT_ID_VALUE=$(git log --format="%H" -n 1)

      - name: Clean up enrichment plugin
        run: |
          rm -rf rudder-alerta-enrichment-plugin

      - name: Create tag
        uses: actions/github-script@441359b1a30438de65712c2fbca0abe4816fa667
        with:
          script: |
            github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: 'refs/tags/${{steps.get_release_version.outputs.releaseVersion}}',
              sha: context.sha
            })
